# File de aliases para matti

alias octo="cd Documentos/R_Home/sturdy-octo-journey/content/post/"
alias nts="cd Documentos/Nts/"
alias rrh="ranger ~/Documentos/R_Home/"
alias rn="ranger ~/Documentos/Nts/"
alias acad="cd Documentos/Acad/"
alias ra="ranger ~/Documentos/Acad/"
alias rd="ranger ~/Documentos/"
alias ri="ranger ~/Imágenes/"
alias rx="ranger ~/.config/"
alias ro="ranger ~/Documentos/R_Home/sturdy-octo-journey/content/post/"
alias 3mes="ncal -M -b -3"
alias rh="ranger ~/"
alias rg="ranger"
alias vc="vim /home/mart/.vimrc"
alias chau="shutdown now"
alias rf="source .bashrc"
alias bk="cd ~/bak/"
