# File de aliases para matti

alias octo="cd ~/Nextcloud/Dox/R_Home/sturdy-octo-journey/content/post/"
alias nts="cd ~/Nextcloud/Dox/Nts/"
alias rrh="ranger ~/Nextcloud/Dox/R_Home/"
alias rn="ranger ~/Nextcloud/Notes/"
alias acad="cd ~/Nextcloud/Dox/Acad/"
alias ra="ranger ~/Nextcloud/Dox/Acad/"
alias rd="ranger ~/Nextcloud/Dox/"
alias rx="ranger ~/.config/"
alias ro="ranger ~/Nextcloud/Dox/R_Home/sturdy-octo-journey/content/post/"
alias 3mes="ncal -M -b -3"
alias rh="ranger ~/"
alias rg="ranger"
alias vc="vim /home/mart/.vimrc"
alias nvc="nvim /home/mart/.config/nvim/init.vim"
alias chau="shutdown now"
alias rf="source .bashrc"
alias bk="cd ~/bak/"
alias nb="newsboat"
alias nbc="~/.newsboat/config"
